language: node_js

node_js:
  - '0.10'

before_script:
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate < test/coverage/**/lcov.info

notifications:
  # publish build status to IRC channel: #once.js
  irc:
    channels:
    - chat.freenode.net#once.js
    on_success: always
    on_failure: always
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
  # publish build status to gitter chat room: https://gitter.im/daniellmb/once.js
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/5a2f080f33d2003480e6
    on_success: always
    on_failure: always
    on_start: false

env:
  - CODECLIMATE_REPO_TOKEN=1a2cfbe782654e9fae7114f1d2a9ab1bcffb34127846ec58c42fd87817f66244